"""End-to-end integration: the full pipeline via the public API.

Parses -> validates -> injects args + context -> executes async -> returns the
spec-shaped ``{data, errors}``.
"""

import fastql
from examples.hello import AppContext, User, make_context, schema


def test_public_api_surface():
    # The primitive authoring surface is importable from the top-level package.
    for name in (
        "Type", "Query", "Mutation", "Field", "Context",
        "build_schema", "execute", "Int", "String", "ID",
    ):
        assert hasattr(fastql, name)


async def test_end_to_end_query_with_args_and_context():
    ctx = AppContext(users={1: User(1, "Ada Lovelace")})

    result = await fastql.execute(
        schema,
        "{ user(id: 1) { id name } ping }",
        context=ctx,
    )

    assert result.errors == []
    assert result.data == {
        "user": {"id": 1, "name": "Ada Lovelace"},
        "ping": "pong",
    }
    assert result.formatted() == {
        "data": {"user": {"id": 1, "name": "Ada Lovelace"}, "ping": "pong"}
    }


async def test_end_to_end_with_variables():
    ctx = AppContext(users={2: User(2, "Grace Hopper")})

    result = await fastql.execute(
        schema,
        "query Lookup($id: Int!) { user(id: $id) { name } }",
        variable_values={"id": 2},
        context=ctx,
    )

    assert result.data == {"user": {"name": "Grace Hopper"}}


async def test_end_to_end_missing_user_returns_null():
    ctx = AppContext(users={})

    result = await fastql.execute(schema, "{ user(id: 99) { id } }", context=ctx)

    # `user` is nullable, so a missing record yields a null with no errors.
    assert result.data == {"user": None}
    assert result.errors == []


async def test_end_to_end_validation_error_has_no_data():
    ctx = AppContext(users={})

    result = await fastql.execute(schema, "{ user(id: 1) { nope } }", context=ctx)

    assert result.executed is False
    assert any("nope" in e.message for e in result.errors)
    assert "data" not in result.formatted()


async def test_end_to_end_introspection():
    result = await fastql.execute(schema, "{ __schema { queryType { name } } }")
    assert result.data == {"__schema": {"queryType": {"name": "Query"}}}


async def test_end_to_end_computed_field_and_query_class():
    result = await fastql.execute(
        schema,
        "{ user(id: 1) { id name loudName } ping }",
        context=make_context(),
    )
    assert result.errors == []
    assert result.data == {
        "user": {"id": 1, "name": "Ada Lovelace", "loudName": "ADA LOVELACE"},
        "ping": "pong",
    }


def test_autogenerated_constructor_on_example_type():
    # The example's User has no hand-written __init__.
    assert User(1, "Ada") == User(id=1, name="Ada")
    assert "Ada" in repr(User(1, "Ada"))
