"""End-to-end integration: the full pipeline via the public API.

Parses -> validates -> injects args + context -> executes async -> returns the
spec-shaped ``{data, errors}``. Runs against the ``examples.app`` showcase schema.
"""

import fastql
from examples.app import BATCH_CALLS, User, make_context, reseed, schema


def test_public_api_surface():
    # The primitive authoring surface is importable from the top-level package.
    for name in (
        "Type", "Query", "Mutation", "Field", "Context",
        "build_schema", "execute", "Int", "String", "ID",
    ):
        assert hasattr(fastql, name)


async def test_end_to_end_query_with_args_and_context():
    result = await fastql.execute(
        schema,
        "{ user(id: 1) { id name } ping }",
        context=make_context(),
    )

    assert result.errors == []
    assert result.data == {
        "user": {"id": 1, "name": "Ada Lovelace"},
        "ping": "pong",
    }
    formatted = result.formatted()
    assert formatted["data"]["ping"] == "pong"
    # The example schema attaches schema-wide extensions, surfaced under `extensions`.
    assert "timing" in formatted["extensions"]
    assert "resolverCount" in formatted["extensions"]


async def test_end_to_end_with_variables():
    result = await fastql.execute(
        schema,
        "query Lookup($id: Int!) { user(id: $id) { name } }",
        variable_values={"id": 2},
    )

    assert result.data == {"user": {"name": "Grace Hopper"}}


async def test_end_to_end_missing_user_returns_null():
    result = await fastql.execute(schema, "{ user(id: 99) { id } }")

    # `user` is nullable, so a missing record yields a null with no errors.
    assert result.data == {"user": None}
    assert result.errors == []


async def test_end_to_end_validation_error_has_no_data():
    result = await fastql.execute(schema, "{ user(id: 1) { nope } }")

    assert result.executed is False
    assert any("nope" in e.message for e in result.errors)
    assert "data" not in result.formatted()


async def test_end_to_end_introspection():
    result = await fastql.execute(schema, "{ __schema { queryType { name } } }")
    assert result.data == {"__schema": {"queryType": {"name": "Query"}}}


async def test_end_to_end_computed_field():
    result = await fastql.execute(
        schema, "{ user(id: 1) { id name loudName } ping }"
    )
    assert result.errors == []
    assert result.data == {
        "user": {"id": 1, "name": "Ada Lovelace", "loudName": "ADA LOVELACE"},
        "ping": "pong",
    }


async def test_end_to_end_dataloader_batches_posts():
    # Querying posts across many users triggers a single batched load (no N+1).
    reseed()
    BATCH_CALLS.clear()

    # A context is required for per-request loader caching (and thus batching).
    result = await fastql.execute(
        schema, "{ users { name posts { title } } }", context=make_context()
    )

    assert result.errors == []
    assert result.data == {
        "users": [
            {
                "name": "Ada Lovelace",
                "posts": [
                    {"title": "On the Analytical Engine"},
                    {"title": "Notes on Note G"},
                ],
            },
            {"name": "Grace Hopper", "posts": [{"title": "The First Compiler"}]},
        ]
    }
    # Both users' posts loaded in one batch call, not one per user.
    assert BATCH_CALLS == [[1, 2]]


def test_autogenerated_constructor_on_example_type():
    # The example's User has no hand-written __init__.
    assert User(1, "Ada") == User(id=1, name="Ada")
    assert "Ada" in repr(User(1, "Ada"))
